#!/usr/bin/env bash
# 外部 skill の導入状態を Claude / Codex へ同期し、管理外の skill を壊さない契約を検証する。
set -u

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
SCRIPT="$REPO/agent-shared/bin/managed-skills.sh"
PASS=0
FAIL=0

if [ ! -f "$SCRIPT" ]; then
  echo "NG: managed-skills implementation is missing"
  exit 1
fi

ok() { PASS=$((PASS + 1)); echo "ok: $1"; }
ng() { FAIL=$((FAIL + 1)); echo "NG: $1"; }
assert() { local description="$1"; shift; if "$@"; then ok "$description"; else ng "$description"; fi; }

TMP="$(mktemp -d "${TMPDIR:-/tmp}/managed-skills.XXXXXX")" || exit 1
trap 'rm -rf "$TMP"' EXIT HUP INT TERM

DOTFILES="$TMP/dotfiles"
HOME_DIR="$TMP/home"
mkdir -p "$DOTFILES/agent-shared/bin" "$DOTFILES/.git/info" \
  "$HOME_DIR/.claude/skills" "$HOME_DIR/.agent-shared/skills" "$TMP/bin"
git -C "$DOTFILES" init -q
cp "$SCRIPT" "$DOTFILES/agent-shared/bin/managed-skills.sh"
printf '# generated by managed-skills.sh; do not edit\n' >"$DOTFILES/agent-shared/managed-skills.tsv"
: >"$DOTFILES/.git/info/exclude"
cat >"$DOTFILES/.gitignore" <<'EOF'
/claude/*
!/claude/skills/
!/claude/skills/**
/codex/*
!/codex/skills/
!/codex/skills/**
EOF

cat >"$TMP/bin/gh" <<'EOF'
#!/usr/bin/env bash
set -u
printf '%s\tprompt=%s\n' "$*" "${GH_PROMPT_DISABLED:-}" >>"$FAKE_GH_CALLS"

[ "${1:-}" = skill ] || exit 2
[ "${2:-}" != --help ] || exit 0
case "${2:-}" in
  install)
    repo="${3:-}"
    selector="${4:-}"
    shift 4
    destination=
    while [ "$#" -gt 0 ]; do
      case "$1" in
        --dir) destination="$2"; shift 2 ;;
        *) shift ;;
      esac
    done
    name="${selector%@*}"
    case "$name" in */SKILL.md) name="$(basename "$(dirname "$name")")" ;; *) name="$(basename "$name")" ;; esac
    mkdir -p "$destination/$name"
    if [ "${FAKE_GH_PARTIAL_ONCE:-}" = "$name" ] && [ ! -e "$FAKE_GH_FAILED_ONCE" ]; then
      printf 'partial\n' >"$destination/$name/SKILL.md"
      : >"$FAKE_GH_FAILED_ONCE"
      exit 1
    fi
    cat >"$destination/$name/SKILL.md" <<SKILL
---
description: Test skill
metadata:
    github-path: skills/$name
    github-pinned: pinned-version
    github-ref: refs/heads/main
    github-repo: https://github.com/$repo
    github-tree-sha: 0123456789abcdef
name: $name
---
body
SKILL
    ;;
  update)
    name="${3:-}"
    shift 3
    destination=
    while [ "$#" -gt 0 ]; do
      case "$1" in
        --dir) destination="$2"; shift 2 ;;
        *) shift ;;
      esac
    done
    printf 'updated\n' >>"$destination/$name/SKILL.md"
    ;;
  *) exit 2 ;;
esac
EOF
chmod +x "$TMP/bin/gh"

export HOME="$HOME_DIR"
export PATH="$TMP/bin:$PATH"
export FAKE_GH_CALLS="$TMP/gh-calls"
export FAKE_GH_FAILED_ONCE="$TMP/gh-failed-once"

run_manager() {
  bash "$DOTFILES/agent-shared/bin/managed-skills.sh" "$@" >"$TMP/output" 2>&1
}

if run_manager add example/skills formatter; then
  assert "add defaults to both agents" test "$(tail -n 1 "$DOTFILES/agent-shared/managed-skills.tsv")" = $'formatter\texample/skills\tformatter\tclaude,codex'
  assert "add installs the Claude copy" test -f "$HOME_DIR/.claude/skills/formatter/.dotfiles-managed-skill"
  assert "add installs the Codex copy" test -f "$HOME_DIR/.agent-shared/skills/formatter/.dotfiles-managed-skill"
  assert "install runs without interactive prompts" grep -q $'^skill install .*\tprompt=1$' "$FAKE_GH_CALLS"
  assert "managed copies stay out of Git status" sh -c '
    git -C "$1" check-ignore -q claude/skills/formatter/.dotfiles-managed-skill &&
      git -C "$1" check-ignore -q codex/skills/formatter/.dotfiles-managed-skill
  ' sh "$DOTFILES"
else
  ng "add defaults to both agents"
  ng "add installs the Claude copy"
  ng "add installs the Codex copy"
  ng "install runs without interactive prompts"
  ng "managed copies stay out of Git status"
fi

mkdir -p "$HOME_DIR/.claude/skills/authored"
printf 'keep\n' >"$HOME_DIR/.claude/skills/authored/SKILL.md"
if run_manager remove formatter; then
  assert "remove deletes manager-owned copies" test ! -e "$HOME_DIR/.claude/skills/formatter"
  assert "remove preserves authored skills" test -f "$HOME_DIR/.claude/skills/authored/SKILL.md"
else
  ng "remove deletes manager-owned copies"
  ng "remove preserves authored skills"
fi

mkdir -p "$HOME_DIR/.claude/skills/collision"
printf 'authored\n' >"$HOME_DIR/.claude/skills/collision/SKILL.md"
if run_manager add example/skills collision; then
  ng "add rejects an authored-skill collision before recording it"
else
  assert "add rejects an authored-skill collision before recording it" \
    sh -c '! grep -q "^collision[[:space:]]" "$1"' sh "$DOTFILES/agent-shared/managed-skills.tsv"
fi
[ -n "$(grep '^collision[[:space:]]' "$DOTFILES/agent-shared/managed-skills.tsv" || true)" ] \
  && run_manager remove collision

export FAKE_GH_PARTIAL_ONCE=retryable
if run_manager add example/skills retryable claude; then
  ng "a partial first install remains retryable"
else
  assert "a failed first install leaves no blocking destination" test ! -e "$HOME_DIR/.claude/skills/retryable"
fi
unset FAKE_GH_PARTIAL_ONCE
if run_manager sync; then
  assert "a partial first install remains retryable" test -f "$HOME_DIR/.claude/skills/retryable/.dotfiles-managed-skill"
else
  ng "a partial first install remains retryable"
fi
run_manager remove retryable || ng "retryable fixture cleanup"

run_manager add example/skills reviewer both || ng "fork fixture installs"
printf 'local change\n' >>"$HOME_DIR/.claude/skills/reviewer/SKILL.md"
printf 'local change\n' >>"$HOME_DIR/.agent-shared/skills/reviewer/SKILL.md"
if run_manager fork reviewer; then
  assert "fork preserves the current contents" grep -q '^local change$' "$HOME_DIR/.claude/skills/reviewer/SKILL.md"
  assert "fork removes GitHub update metadata" sh -c '! grep -q "github-" "$1"' sh "$HOME_DIR/.claude/skills/reviewer/SKILL.md"
  assert "fork makes the skill unmanaged" test ! -e "$HOME_DIR/.claude/skills/reviewer/.dotfiles-managed-skill"
  assert "fork removes the desired-state record" sh -c '! grep -q "^reviewer[[:space:]]" "$1"' sh "$DOTFILES/agent-shared/managed-skills.tsv"
else
  ng "fork preserves the current contents"
  ng "fork removes GitHub update metadata"
  ng "fork makes the skill unmanaged"
  ng "fork removes the desired-state record"
fi

echo "PASS=$PASS FAIL=$FAIL"
[ "$FAIL" -eq 0 ]
